### ISSUE TITLE
Transposer

### ISSUE THREAD

**Issue by anusfoil** [rbdannenberg/soundcool#13]
1. Needs implementation of audio object.

**Comment by rbdannenberg** [comment]
Cannot connect to input.

**Comment by im-Amitto** [comment]
I think it's not implemented yet and we are also not planning to have it in
our first release so let's take this one as a low priority issue.

**Comment by rbdannenberg** [comment]
Should Soundcool runnable now? I can't get it to run from sources on Mac 
or Linux. -Roger

**Comment by im-Amitto** [comment]
@rbdannenberg I just tested the current master and it's working fine.
Let me know if it's still not working for you then I can test the sources in a fresh system.

**Comment by rbdannenberg** [comment]
I was afraid of that. I'll try again with a fresh start. -Roger

**Comment by ankit204** [comment]
Seems to be working in 7ca9d24040a389f02fc25d58ca2b75cfade181d6.
