### ISSUE TITLE
Structure of the project

### ISSUE THREAD

**Issue by anusfoil** [rbdannenberg/soundcool#16]
Currently the frontend of this project is in two parts: The server-side rendered dashboard (client folder) that includes home page, login page, etc; The project editor (actual soundcool app) that's built from create-react-app (client2 folder). Is it a good idea to have two kinds of ways to use React? If someone comes up a better design please restructure the project.

**Comment by im-Amitto** [comment]
@Kristin33  @rbdannenberg successfully merged both of react frontend into a single project so we don't need to handle two separate projects.
