### ISSUE TITLE
Implement the saving of project back to database

### ISSUE THREAD

**Issue by anusfoil** [rbdannenberg/soundcool#17]
Currently we can only load project by fetching user's data from database, but have yet implemented the way to save it back to the database after user make changes to their project (the `save` button currently is just a placeholder (it does copy all the redux state information and make a variable in local storage, but we need to implement it sending the information to backend and back to database).

**Comment by im-Amitto** [comment]
@Kristin33 @rbdannenberg   removing it as this functionality has been successfully added
