### ISSUE TITLE
Implement creating new projects and new users

### ISSUE THREAD

**Issue by anusfoil** [rbdannenberg/soundcool#22]
There is a create button in the navigation bar, it will take us to the project editor page and allow users to play with soundcool without log in as an existing user. But when the user decides to save the project, we should ask them to register (we have a register scheme) and then save the project under their account.

**Comment by im-Amitto** [comment]
Working on it

**Comment by im-Amitto** [comment]
@Kristin33 @rbdannenberg closing the issue as the feature has been successfully implemented
