### ISSUE TITLE
Cannot drag objects in column view.

### ISSUE THREAD

**Issue by rbdannenberg** [rbdannenberg/soundcool#25]
It should be possible to drag objects to new location (change order of objects) in non-floating view.

**Comment by im-Amitto** [comment]
@rbdannenberg I remeber that @ameykpatel  have implemented the drag functionality in early version of soundcool but i guess it do not exist in the codebase anymore. I will add it again.

**Comment by im-Amitto** [comment]
Solved in bd9db3290aa61eaa945d96684a033a43c63e769e
