### ISSUE TITLE
Input/output patch buttons/indicators coloring.

### ISSUE THREAD

**Issue by rbdannenberg** [rbdannenberg/soundcool#26]
When you connect an object to another object, the connection should show the color as well as the short name of the connected object. When you mouse over the connection button, the connected objects should highlight.

**Comment by im-Amitto** [comment]
@ankit204 you are more familier than me on this topic. if you are't busy can you please look ino this?

**Comment by im-Amitto** [comment]
Fixed in 147a4385d47e14d383f8f78bc01d34cf8bd63305
