### ISSUE TITLE
Login does not work.

### ISSUE THREAD

**Issue by rbdannenberg** [rbdannenberg/soundcool#27]
When I log in as user1@welcome.com, a "Session expired" message appears. The interface displays a "Logout" button, but when I try to open a sound, I get a message to login first.

**Comment by im-Amitto** [comment]
@rbdannenberg I'm not able to reproduce the error, can you please receord a video or share terminal logs.

**Comment by ankit204** [comment]
Logging in worked after some debugging. Closing it.
