### ISSUE TITLE
soundcool main surface modified

### ISSUE THREAD

**Issue by masaeal** [rbdannenberg/soundcool#32]
[Soundcool main surface.zip](https://github.com/rbdannenberg/soundcool/files/4388100/Soundcool.main.surface.zip)

[soundcool test.zip](https://github.com/rbdannenberg/soundcool/files/4388096/soundcool.test.zip)

**Comment by rbdannenberg** [comment]
I think this was either incorporated already or it's obsolete. Closing now.
