### ISSUE TITLE
Audio Settings button on Speaker module seems to do nothing. 

### ISSUE THREAD

**Issue by rbdannenberg** [rbdannenberg/soundcool#34]
We should comment out the code the creates the Speaker module has "Audio Settings" button so it does not appear, but if we want to use it later, it will be easy to restore.

Are there any audio settings we want to control? Should  we open the browser audio settings preferences from Javascript? (Firefox seems to have no interesting settings for audio.) Can we open Linux Settings for audio (and do we want to?) Audio Settings panel is the closest thing to the Max MSP audio settings on the Max version of Soundcool.

**Comment by im-Amitto** [comment]
I will fix it within an hour or two.

**Comment by anusfoil** [comment]
I now commented out the button. Let me know if we decide any audio settings that to change

**Comment by ankit204** [comment]
This is fixed. Reopen if we want to expose configurable(s) like latency hint and audio sampling rate to the end user.
