### ISSUE TITLE
Column view has only one column.

### ISSUE THREAD

**Issue by rbdannenberg** [rbdannenberg/soundcool#35]
Column view should have at least 2 columns. Probably user should be able to specify how many columns. Probably 3 would be the default -- whatever you think would fit a normal screen width. Maybe the default could be set according to the screen width when you first create the project.

**Comment by im-Amitto** [comment]
@rbdannenberg  
Let's set the default to 2 columns and add functionality to manipulate the column numbers as desired.
P.S. Will be fixed within 24 hours

**Comment by im-Amitto** [comment]
Fixed :) Few options on GitHub aren't working for now including close issue so feel free to close it once it starts working.
