### ISSUE TITLE
Improvements on new create project page

### ISSUE THREAD

**Issue by im-Amitto** [rbdannenberg/soundcool#40]
- [ ] The buttons should not be placed in the bottom right(They won't be clickable once you spawn a few components due to z-index.Also, they will look absurd floating in the middle of the screen when user scroll down)
- [X] Move focus on the component when they are spawned
- [ ] Move the component spawners with scroll
- [ ] Fullscreen button can be added(at least in floating mode)

**Comment by rbdannenberg** [comment]
I think this issue will go away with #47 -- feel free to close this if you agree.

**Comment by im-Amitto** [comment]
Closing the issue since #47 covers all the points
