### ISSUE TITLE
Replace url-loader with file-loader

### ISSUE THREAD

**Issue by im-Amitto** [rbdannenberg/soundcool#41]
@Kristin33 I think it will be better if we use `file-loader` in place of `url-loader` for loading images and other media. Using `url-loader` attach the media files in the code by converting them into base64 and it comes with a limit so there will be cons of using it.
Files will be loaded even when they are not in use.
The bundle file size will increase.
We may never know if we needed to load a file exceeding the limit.
It's your call in the end.

**Comment by anusfoil** [comment]
sounds good, I will replace it today
