### ISSUE TITLE
Script Testing

### ISSUE THREAD

**Issue by im-Amitto** [rbdannenberg/soundcool#43]
@rbdannenberg @Kristin33 @ankit204 
Please drop any suggestion/error regarding the scripts in this issue

- [ ] Have Bugs
- [ ] Need Improvements
- [ ] Script to update the database

**Comment by anusfoil** [comment]
I am encountering trouble running the soundcool binary on macOS:

`(base) Huans-MBP:soundcool huanzhang$ chmod +x soundcool`
`(base) Huans-MBP:soundcool huanzhang$ ./soundcool`
`-bash: ./soundcool: cannot execute binary file`

`(base) Huans-MBP:soundcool huanzhang$ file soundcool`
`soundcool: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/l, for GNU/Linux 2.6.32, BuildID[sha1]=ced22c55047f27eb03ab4ff5b5e7628657fecf17, with debug_info, not stripped`

The three automated bash scripts works nicely on my system!

**Comment by im-Amitto** [comment]
I will check on it ASAP.  Not sure but maybe some configuration is os
dependent.

**Comment by anusfoil** [comment]
Thanks! The error printed out seems to be every short and I am also unsure what other information I could provide.
I did some search and it's probably because it's in ELF format, while Mac OS X uses the Mach-O format for binaries?

**Comment by im-Amitto** [comment]
Oh, did't knew about that.

**Comment by im-Amitto** [comment]
@Kristin33 I don't have a mac system so I can't really test it but can you try the below commands and let me know if it works
npm install -g nexe
nexe index.js -o soundcool2 (in the build directory /soundcool)
./soundcool2

**Comment by anusfoil** [comment]
The first 2 commands executed successfully and soundcool2 runs, but seems to have problems with node.

`(base) Huans-MBP:soundcool huanzhang$ ./soundcool2`
`internal/modules/cjs/loader.js:805`
 ` return process.dlopen(module, path.toNamespacedPath(filename));`
`                 ^`

`Error: dlopen(/Users/huanzhang/07MusicTech/soundcool/soundcool/lib/binding/bcrypt_lib.node, 1): no suitable image found.  Did find:
	/Users/huanzhang/07MusicTech/soundcool/soundcool/lib/binding/bcrypt_lib.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/huanzhang/07MusicTech/soundcool/soundcool/lib/binding/bcrypt_lib.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:805:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.module.exports.module.exports (/Users/huanzhang/07MusicTech/soundcool/soundcool/index.js:62666:18)
    at __webpack_require__ (/Users/huanzhang/07MusicTech/soundcool/soundcool/index.js:22:30)
    at Object.module.exports.stringFromCharCode (/Users/huanzhang/07MusicTech/soundcool/soundcool/index.js:10856:16)
    at __webpack_require__ (/Users/huanzhang/07MusicTech/soundcool/soundcool/index.js:22:30)`

**Comment by im-Amitto** [comment]
I am not sure if i can help much in this one as i am not familiar with
macos.

**Comment by im-Amitto** [comment]
@Kristin33 Any update?

**Comment by im-Amitto** [comment]
@Kristin33 I have added the binary for macOS :)
you can check it out
