### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by anusfoil** [rbdannenberg/soundcool#45]
the speed in player and sample player should:
- be able to enter a specific speed 
- x0 should be a minimum value 0.01

I will look into it

**Comment by rbdannenberg** [comment]
Specifically, clicking on x0 should set speed to 0.01, x1 should set speed to 1.0, and x2 should set speed to 2.0. It's OK but not necessary to have a box to enter arbitrary speeds. The main motivation is just to return to *exactly* 1.0.

**Comment by im-Amitto** [comment]
We can use something like this
Show value while sliding and the major points can be clickable(0x,1x,2x)
![](https://www.syncfusion.com/products/react-js2/control/images/slider/touch.gif)
