### ISSUE TITLE
Draggable view issues 

### ISSUE THREAD

**Issue by anusfoil** [rbdannenberg/soundcool#48]
Draggable view only work when project first opens. After switching view or going to another page it doesn't work. 

to replicate the issue: 
- go to create project page
- check whether you can drag, should be okay
- click floating view: off to change to floating view
- come back to draggable view 

At this point modules can't be dragged to another column.

**Comment by im-Amitto** [comment]
Update: Also only column 1 components are being sent to the floating view

**Comment by im-Amitto** [comment]
Fixed
