### ISSUE TITLE
Mixer audio module two channels question

### ISSUE THREAD

**Issue by anusfoil** [rbdannenberg/soundcool#49]
I am trying to get stereo meter level data from the sc-mixer audio object in order to render it at GUI. I refered to the sc-speaker and it seems to need a ChannelSplitterNode to split the context into 2 channels and put analyzers on each side. But I am not sure how to do that in sc-mixer given that there are multiple nodes. Should I put a ChannelSplitterNode on each of them? @ankit204

**Comment by ankit204** [comment]
I implemented splitting and meters on individual channels for inputs and outputs with these commits: https://github.com/rbdannenberg/soundcool/commit/d3897954b265d162fd3543074174c785382c9da4, https://github.com/rbdannenberg/soundcool/commit/bb877ca7d7c483e10833decbcb9b2dc2077c515b.

All `get*AudioData` APIs should now pack and return left and right meter level. Reopen this issue if you run into any problems.
