### ISSUE TITLE
Implement suspending and resuming of a patch

### ISSUE THREAD

**Issue by ankit204** [rbdannenberg/soundcool#50]
ScSpeakers should implement suspend and resume playback of a soundcool patch. This is done by clicking the button highlighted in the picture below. Note to self: use AudioContext's `suspend` and `resume` methods.

![Screen Shot 2020-04-28 at 10 57 31 PM](https://user-images.githubusercontent.com/12268893/80557461-ff5abd00-89a4-11ea-9356-97403847a51d.png)

**Comment by rbdannenberg** [comment]
This seems to be implemented, but it pops, so it's not really suitable for live performance. Clicking the speaker should smoothly ramp down to zero as if a volume control with smoothing was set to zero.

**Comment by rbdannenberg** [comment]
Another problem is when you restore speaker, the GUI seems to restore the "enable sound output" state, but if you saved with sound off, sound is on when you open the saved project.

**Comment by anusfoil** [comment]
fixed the restoring issue

**Comment by ankit204** [comment]
@Kristin33 , muting on this button click is wrong. Essentially, clicking this button means stop producing audio samples and not keep producing samples and multiply it with zero. I'll fix this.

**Comment by ankit204** [comment]
ac2705de3cb43b181ea3496c9573be03f0c8cfd3 implements suspending and resuming of a patch. Suspend ensures the audio clock is suspended and reduces CPU/power consumption. Also implements smoothing to avoid sound artifacts.
