### ISSUE TITLE
"Register to save" button doesn't work when running sever using binary

### ISSUE THREAD

**Issue by ankit204** [rbdannenberg/soundcool#54]
Steps:
1. Click on Create Project
2. Edit the project
3. Click on Register to save button

Registering in the pop-up dialog doesn't work.

**Comment by im-Amitto** [comment]
@ankit204 I'm not able to reproduce the error. Let me know if anyone else can?
cc: @Kristin33 @rbdannenberg @ameykpatel

**Comment by im-Amitto** [comment]
Closing the issue
