### ISSUE TITLE
Shrink module size

### ISSUE THREAD

**Issue by anusfoil** [rbdannenberg/soundcool#55]
I did shrink down the size of module by css transform, and the left-right margin has been dealt with by reducing column size. However there is still a chunk of height margin at the bottom of the module so that modules don't stick together. I was investigating it today for a while but found no clue :( I think it's not the problem of drag and drop module, but the css transform. I could just set a smaller height, but since different modules have different height, a fixed set wouldn't work. 

<img width="1232" alt="WX20200504-234844@2x" src="https://user-images.githubusercontent.com/31784445/81033487-e305c700-8e61-11ea-8438-833897b9e999.png">
Any help will be very appreciated!

**Comment by im-Amitto** [comment]
@Kristin33 I will look into it :)

**Comment by im-Amitto** [comment]
@Kristin33 
You re using the CSS `scale` property which actually transforms how the element looks. In short, the component will surely appear 0.8 times but for other components, it's still the same size hence they don't get reordered.
So the actual height won't change using `scale`

**Comment by ankit204** [comment]
Notes: Here's the relevant part of the [`transform` CSS spec](https://drafts.csswg.org/css-transforms/#module-interactions): "This module defines a set of CSS properties that affect the visual rendering of elements to which those properties are applied; these effects are applied after elements have been sized and positioned according to the visual formatting model from [CSS2]. Some values of these properties result in the creation of a containing block, and/or the creation of a stacking context.". I am work on the fix.

**Comment by ankit204** [comment]
Fixed in 6259d64f285c88796d31d00fd1d2b164bbe7b0fc and ede4e23b8b42b4c5b0bfbc2e88b46a83f34662ea.
