### ISSUE TITLE
Youtube link resolution

### ISSUE THREAD

**Issue by ankit204** [rbdannenberg/soundcool#60]
If we add multiple Youtube links from Sounds tab, it appears the audio buffer is named as "Youtube" with a unique "Id". It is hard to know which audio buffer corresponds to which Youtube link when selecting audio buffer in Player. Assuming names are easier to remember than ID, add functionality to rename user/sounds?

**Comment by im-Amitto** [comment]
@ankit204 Will fix it in a few days.

**Comment by im-Amitto** [comment]
Fixed and closed
