### ISSUE TITLE
MODULES TEST

### ISSUE THREAD

**Issue by masaeal** [rbdannenberg/soundcool#62]
Hi all,
i have been testing soundcool and i have made some notes and video where you can see  fails about the modules that doesn't work totally correct.

[MODULES TEST.docx](https://github.com/rbdannenberg/soundcool/files/4621674/MODULES.TEST.docx)

[Test.zip](https://github.com/rbdannenberg/soundcool/files/4621677/Test.zip)

**Comment by rbdannenberg** [comment]
I moved the notes into various other issues and module status page on the wiki.
