### ISSUE TITLE
Linear Volume and Frequency Controls

### ISSUE THREAD

**Issue by rbdannenberg** [rbdannenberg/soundcool#67]
Linear volume controls are not good enough. Change them all to x^4. That is, convert the slider value to the range [0, 1]. Then raise that to the 4th power. The result is the Web Audio scale factor (amplitude multiplier). 

Ideally, encapsulate that as linear_to_volume(x) in case we don't like the x^4 rule.

Frequency controls have the same problem. SignalGen frequency should go exponentially from 40 to 10,000, and users can type in frequencies outside that range.

Again, encapsulate that as linear_to_frequency(x) in case we want to change the rule, and use some constants, e.g. LOWEST_FREQUENCY and HIGHEST_FREQUENCY, to define the range.

Notes: In some since, amplitude should increase exponentially with slider position to approximate our perception of loudness, but exponentials never go to total silence (0), and professional mixers usually have finer volume control at the top end than at the bottom. x^4 seems like a good compromise among all these ideas.

**Comment by ankit204** [comment]
Implemented in b2363676f41399c789e1df01368b65c6015e0493 and e67061ec9ea3a599b3938bf6c02475580df809d8.

**Comment by rbdannenberg** [comment]
Sorry - I'm editing my previous comment because my installation was not up-to-date. Still, I'm reopening because the SignalGen frequency control shows the wrong frequency in the text box, and the frequency range is too high. It seems to go down to around 0.01Hz instead of 40Hz as we discussed.

**Comment by ankit204** [comment]
Fixed in https://github.com/rbdannenberg/soundcool/commit/7f8e1447776079c41e41321167fe5105d9ba89b7.
