### ISSUE TITLE
Audio parameter updates need low-pass filter.

### ISSUE THREAD

**Issue by rbdannenberg** [rbdannenberg/soundcool#68]
When you adjust volume, you here crackly sounds indicating that the amplitude changes are instantaneous steps. This causes discontinuities and make volume changes unusable in performance.

The solution is some kind of smoothing either through low-pass filter, linear ramp between values. A particularly low-cost but workable computation is an exponential decay, e.g. on every sample make the new amplitude a depend on the slider value x and the previous amplitude a':

a = (1 - alpha)*a' + alpha*x

where alpha is nearly 1, e.g. 0.999.

This is cheaper than a linear ramp to compute, but we don't get to write the inner DSP loops, so whatever Web Audio provides will have to do.

**Comment by ankit204** [comment]
Implemented a fix with commit: da215c6b39c77d500b527f690c104a97adeba256. I used `exponentialRampToValueAtTime` method to schedule a ramp to reach the desired value in `0.5` seconds from the time the change in volume is requested. Re-open if anything looks wrong.

Note: `exponentialRampToValueAtTime` prevents us from setting the min volume to 0 (ref: https://webaudio.github.io/web-audio-api/#dom-audioparam-exponentialramptovalueattime). We default to `1.40130e-45` for any non-positive value.

**Comment by ankit204** [comment]
I replaced `exponentialRampToValueAtTime` implementation with `setTargetAtTime` setting `timeConstant=5e-3s` in this commit: 4ed1d92887ed1ccea6a2a0cc91d614c3c74f4c4f. We get to set min param value to `0` now. This smoothing removes artifacts when tested for volume changes on a 100Hz sine wave. @rbdannenberg, thoughts?

**Comment by rbdannenberg** [comment]
I think the time constant is too short or maybe not working at all -- when I alternately click loud/soft positions on SignalGen and Player, the output pops quite a lot. Can we try 50ms? (5e-2 s?) I think that would not produce any noticeable lag, and be a lot smoother.

**Comment by rbdannenberg** [comment]
Sorry -- I had a problem updating. After fixing and actually installing your fixed code, the smoothing sounds OK.
