### ISSUE TITLE
Save project failed: OS X and Firefox

### ISSUE THREAD

**Issue by rbdannenberg** [rbdannenberg/soundcool#72]
Is Project: Save supposed to work? I created a project with just a sample player connected to speaker.
After Project:Save and entering name and description, I get
Cannot POST /project-editor/new
on the web page, and 
Content Security Policy: The page’s settings blocked the loading of a resource at http://localhost:5000/favicon.ico (“default-src”). FaviconLoader.jsm:165:19
reported on the Browser console.
I don't see any errors reported in the terminal window running the backend.

**Comment by im-Amitto** [comment]
@rbdannenberg Looks like a cors issue. I will fix it this week.

**Comment by im-Amitto** [comment]
I tested a few things and looks like it's OS X related issue

**Comment by im-Amitto** [comment]
@rbdannenberg I pushed a patch in my last commit. Let me know if it works for you.

**Comment by anusfoil** [comment]
I can't replicate Roger's error on my mac and Firefox, but I have another error that's related to saving: I was trying to save a player connect to speaker, with a sound file selected. This is what I got in backend terminal:

`url.js:154
    throw new ERR_INVALID_ARG_TYPE('url', 'string', url);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
    at Url.parse (url.js:154:11)
    at Object.urlParse [as parse] (url.js:148:13)
    at doDownload (/Users/.../soundcool/src/backend/node_modules/miniget/dist/index.js:90:28)
    at process._tickCallback (internal/process/next_tick.js:61:11)`

It seems to be just a url fetching issue, but I can't find with function directs to here

**Comment by im-Amitto** [comment]
I will look into it and get back to you guys.

**Comment by rbdannenberg** [comment]
I tested again. Still same error with OS X and Firefox on an updated version from github sources yesterday. I have no idea why my results are different from Kristin's.

**Comment by im-Amitto** [comment]
Can you please please drop a screenshot of the error as i can't
reproduce the issue.

**Comment by rbdannenberg** [comment]
This is very strange -- I just ran the same test again and it worked. I don't know if something was in the cache or what. I assume Kristin's problem still holds.
