### ISSUE TITLE
Should sound continue running when user selects Project:Open?

### ISSUE THREAD

**Issue by rbdannenberg** [rbdannenberg/soundcool#74]
It seems that Web Audio keeps computing sound when user enters dialogs like Project:Open. At that point, user cannot adjust volumes but sounds are still playing. I can see why something like saving should leave sound running (maybe), but I think it's better to shut down sound when you are not looking at the patch to make sure users don't get to a point where they can't shut off the sound.

**Comment by anusfoil** [comment]
Fixed: now sound is shut down when user leaves the project editor page; all module states are cleared and audio objects are destroyed; page will notify user to save before leaving
