### ISSUE TITLE
Close buttons on modules may not work completely

### ISSUE THREAD

**Issue by rbdannenberg** [rbdannenberg/soundcool#77]
Create a speaker module
Create a signalGen module
Make some sound
While sound is playing, click the delete button on the signalGen module
Click the delete button on the speaker module
-> sound is still playing(!); the oscillator should have been disconnected and deleted when the signalGen module was deleted, and same for the speaker.

**Comment by anusfoil** [comment]
I think this is related to #53 , as we have not implemented destroying modules.

In the most recent commit I defined destroying audio object as disconnecting all the web audio nodes inside, so it behave as expected when closing the module and sound is no longer playing. Not sure if this is the optimal way to delete web audio nodes, feel free to reopen this if you spot any error @ankit204

**Comment by rbdannenberg** [comment]
Create SignalGen, Mixer, Speaker
Connect SignalGen to Mixer
Connect Mixer to Speaker
Delete Mixer
Delete the Speaker (speaker is not deleted)
Delete SignalGen (page crashes)
