### ISSUE TITLE
youtube sound no longer working

### ISSUE THREAD

**Issue by anusfoil** [rbdannenberg/soundcool#79]
Today I found that soundcool can no longer use youtube sound: after adding the youtube sound, the resource in the sound page is gray, can't play, and can't be used in project

I remembered it works previously so I traced back to several old version but they all don't work. 

Anyone experiencing similar problem?

**Comment by im-Amitto** [comment]
@Kristin33 
Can you drop the error message you are getting on backend terminal or frontend terminal

**Comment by ankit204** [comment]
Fixed in 7d24f897f77e774739d6ce69eb5ee7d4f56a19f2. Steps to fix this issue on your install:
1. git pull
2. Go to src/backend
3. rm -rf node_modules && npm install (edited by im-Amitto)
