### ISSUE TITLE
"Select a sound page" style sheet 

### ISSUE THREAD

**Issue by anusfoil** [rbdannenberg/soundcool#80]
"Select a sound" page seems to not having a proper style sheet now: 

<img width="799" alt="WX20200605-111943@2x" src="https://user-images.githubusercontent.com/31784445/83833411-7c085600-a71e-11ea-9107-05e42991d9a8.png">

but previously it looks like (and it should):

<img width="794" alt="WX20200605-111805@2x" src="https://user-images.githubusercontent.com/31784445/83833365-58dda680-a71e-11ea-8c68-48655bbd796b.png">

I traced back old commits and noticed that bootstrap stylesheets were removed on the commits about dependencies on May 26th and the page looks like this since then.

**Comment by im-Amitto** [comment]
I added them back 15 or 16 days back i guess.
Closing the issue
