### ISSUE TITLE
pitch & transposer

### ISSUE THREAD

**Issue by anusfoil** [rbdannenberg/soundcool#83]
- Delete the pitch module 
- Transposer range should be -400 ~ 400 cents

**Comment by ankit204** [comment]
Implemented `ScTransposer` in 5bd448fb636f93fa3ada703f5ac69a488cf0149a. 
@rbdannenberg, can you confirm we do not need `ScPitch` module anymore? I'm guessing the [-400, 400] cents range is for `ScPitch` and not fine pitch control in `ScTranspose` - is that right?

**Comment by ankit204** [comment]
ScTransposer related items fixed in https://github.com/rbdannenberg/soundcool/commit/d26d96c86a7dd02f8624fdfdd85d02d79ef263b0.
