### ISSUE TITLE
Save / Restore Patching

### ISSUE THREAD

**Issue by anusfoil** [rbdannenberg/soundcool#91]
I think we implemented this feature before but now it seems broken: 

- log in
- create any two connectable modules, connect them
- save this project
- connection not restored from this saved project

**Comment by rbdannenberg** [comment]
I marked a corresponding element in the Wiki page with 🔴. -Roger

**Comment by ankit204** [comment]
I looked into this. Did the specification of a connection in a project changed recently @Kristin33 @im-Amitto ?

**Comment by anusfoil** [comment]
module connection? I don't think so, the latest change I made was [https://github.com/rbdannenberg/soundcool/blob/master/doc/GUI/Connection%20Spec.pdf](url) which was 3 months ago

**Comment by im-Amitto** [comment]
@rbdannenberg Let's close this as it seems to be working perfectly fine now.
