### ISSUE TITLE
crashing: GranSynth with local storage

### ISSUE THREAD

**Issue by anusfoil** [rbdannenberg/soundcool#93]
We encounter the issue that adding a GranSynth result in project crashing: ` Failed to execute 'setItem' on 'Storage': Setting the value of 'localProject' exceeded the quota.` 

Since we are saving project temporarily in LocalStorage, the size of the buffers in GranSynth seems to exceed the allowed limit. But this doesn't happen for other modules, even with SamplePlayers with long audios (with may also have a large buffer).  

Testing: the project won't crash if we don't initialize audioObj for GranSynth  - so it should be the size of buffer that's too large...

**Comment by im-Amitto** [comment]
@Kristin33 I will fix this one
